momo:
  endpoint: "https://test-payment.momo.vn/v2/gateway/api/create"
  partner-code: ${MOMO_PARTNER_CODE}
  access-key: ${MOMO_ACCESS_KEY}
  secret-key: ${MOMO_SECRET_KEY}
  redirect-url: ${MOMO_REDIRECT_URL}
  notify-url: ${MOMO_NOTIFY_URL}


ghn:
  token: ${GHN_TOKEN}
  shop-id: ${GHN_SHOP_ID}
  shop-phone: ${GHN_SHOP_PHONE}  # Sửa lại số đầy đủ 10 số
  shop-address: ${GHN_SHOP_ADDRESS}
  shop-district-id: ${GHN_SHOP_DISTRICT_ID}
  shop-ward-id: ${GHN_SHOP_WARD_ID}
  # Thêm các config mới:
  api-url: ${GHN_API_URL:"https://dev-online-gateway.ghn.vn/shiip/public-api"}  # Base URL cho test
  sync-enabled: true        # Bật auto-sync data
  sync-on-startup: true     # Sync khi startup
  cache-duration: 24        # Cache data trong 24h
  # Default per-item weight (grams) when product.weight missing
  default-per-item-weight: 500
  # Default required_note to send to GHN. One of: CHOTHUHANG, CHOXEMHANGKHONGTHU, KHONGCHOXEMHANG
  default-required-note: "KHONGCHOXEMHANG"
server:
  port: 8080

spring:
  config:
    import: "optional:file:.env[.properties]"
  datasource:
    url: ${DBMS_CONNECTION}
    password: ${DBMS_PASSWORD}
    username: ${DBMS_USERNAME}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Ho_Chi_Minh
  flyway:
    enabled: false
  jackson:
    time-zone: Asia/Ho_Chi_Minh
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          debug: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: ${GOOGLE_REDIRECT_URI}
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: email
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  signerKey: ${JWT_SIGNER_KEY}
  valid-duration: ${JWT_VALID_DURATION}
  refreshable-duration: ${JWT_REFRESHABLE_DURATION}

initial:
  admin:
    password: ${INITIAL_ADMIN_PASSWORD}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
  secure: true

